language: python
python:
  - "3.12"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test tests

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "us-east-1"
  app: "polls-app"
  env: "polls-app-dev"
  bucket_name: "polls-bucket-swe1"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
